
"use client";

import React from "react";
import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import { FileText, Scale, MessageSquare, AlertCircle } from "lucide-react";

export default function TermsPage() {
  return (
    <main className="min-h-screen pt-20 bg-secondary/5">
      <Navigation />
      
      <section className="bg-primary text-white py-20 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <FileText size={48} className="mx-auto mb-6 opacity-80" />
          <h1 className="font-headline text-5xl font-bold mb-4">Terms of <span className="text-secondary italic">Service</span></h1>
          <p className="text-xl opacity-90 leading-relaxed">
            The guidelines for exploring Rumonge Cultural Trails.
          </p>
        </div>
      </section>

      <section className="py-24 px-6 max-w-4xl mx-auto">
        <div className="bg-white rounded-[2rem] p-12 shadow-xl border space-y-12">
          <div className="space-y-4">
            <h2 className="text-2xl font-bold flex items-center gap-3">
              <Scale className="text-primary" />
              User Agreement
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              By using Rumonge Cultural Trails, you agree to respect the local culture and traditions of Rumonge Commune. 
              Our platform is intended to promote respectful and sustainable tourism.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-2xl font-bold flex items-center gap-3">
              <MessageSquare className="text-primary" />
              Community Guidelines
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Travelers are encouraged to share reviews and pro-tips. We reserve the right to remove any content 
              that is offensive, inaccurate, or disrespectful to the local community or other users.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-2xl font-bold flex items-center gap-3">
              <AlertCircle className="text-primary" />
              AI Recommendations
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Itineraries generated by our AI are for planning purposes only. While we strive for accuracy, 
              travelers should verify opening hours and availability directly with local establishments.
            </p>
          </div>

          <div className="pt-12 border-t text-sm text-muted-foreground italic text-center">
            Last Updated: June 2024. Use of this site constitutes acceptance of these terms.
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
